# Generated by Django 4.2.13 on 2025-08-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0003_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
