# Generated by Django 4.2.13 on 2025-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0004_delete_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        default="usuarios/Denis.jpeg", upload_to="usuarios/"
                    ),
                ),
            ],
        ),
    ]
