# Generated by Django 4.2.13 on 2025-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0005_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                default="usuarios/Denis.jpg", upload_to="usuarios/"
            ),
        ),
    ]
